### ISSUE TITLE
关闭当前Activity,再次打开,直接报这个错该怎么解决?

### ISSUE THREAD

**Issue by roybill** [yhaolpz/FixedFloatWindow#113]
错误提示:  Caused by: java.lang.IllegalArgumentException: FloatWindow of this tag has been added, Please set a new tag for the new FloatWindow

我是这样写的：
    FloatWindow
                .with(getApplicationContext())
                .setView(imageView)
                .setWidth(Screen.width, 0.2f) //设置悬浮控件宽高
                .setHeight(Screen.width, 0.2f)
                .setX(Screen.width, 0.8f)
                .setY(Screen.height, 0.3f)
                .setMoveType(MoveType.active)
                .setMoveStyle(500, new BounceInterpolator())
                .setFilter(true, Yiyilingliu.class) //只在指定Activity显示悬浮按钮
                .setViewStateListener(mViewStateListener)
                .setPermissionListener(mPermissionListener)
                .setDesktopShow(true)
                .build();

**Comment by tx123456** [comment]
> 错误提示: Caused by: java.lang.IllegalArgumentException: FloatWindow of this tag has been added, Please set a new tag for the new FloatWindow
> 
> 我是这样写的：
> FloatWindow
> .with(getApplicationContext())
> .setView(imageView)
> .setWidth(Screen.width, 0.2f) //设置悬浮控件宽高
> .setHeight(Screen.width, 0.2f)
> .setX(Screen.width, 0.8f)
> .setY(Screen.height, 0.3f)
> .setMoveType(MoveType.active)
> .setMoveStyle(500, new BounceInterpolator())
> .setFilter(true, Yiyilingliu.class) //只在指定Activity显示悬浮按钮
> .setViewStateListener(mViewStateListener)
> .setPermissionListener(mPermissionListener)
> .setDesktopShow(true)
> .build();

我也遇到这个问题了，你解决了吗
