### ISSUE TITLE
修改activity启动方式，floatView会默认隐藏，出来后，显示 一下马上又隐藏

### ISSUE THREAD

**Issue by stackBreakerX** [yhaolpz/FixedFloatWindow#73]
Intent intent = new Intent(this, MainActivity.class);
			intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);

**Comment by QXH313** [comment]
出现同样的状况

**Comment by stackBreakerX** [comment]
楼主能不能看看这个问题

**Comment by LxzBUG** [comment]
好像是FloatLifecycle 生命周期的问题 第一次进来显示一下 就隐藏了 将FloatLifecycle类startCount 变量默认值改成1 就可以了 @AlexZQS @QXH313

**Comment by stackBreakerX** [comment]
已解决，谢谢了，本来不想把代码拔下来的，问题是为什么不把startCount设置为1，感觉也没有影响什么

**Comment by cnmao** [comment]
我这边也是一闪一闪的  ， 修改startCount  无效

**Comment by cheegon** [comment]
问题的原因是,FloatLifecycle 注册时机并不是在Application初始化中,导致统计的startCount和resumeCount个数不准确

1.在 Application中,注册registerActivityLifecycleCallbacks,
2.在注册的ActivityLifecycleCallbackImp中,统计activityCount,当onActivityStarted时,activityCount++;当onActivityStopped时,activityCount--
3.在FloatLifecycle 的构造方法中,startCount和resumeCount都赋值为ActivityLifecycleCallbackImp中的activityCount

**Comment by huangxiaoyu** [comment]
setDesktopShow(true) 设置桌面显示就行了,会一直显示.不想在左面显示的效果,在ondestoty的时候销毁,就不会在桌面显示
